In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")

In [4]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

Information about the dataset

In [5]:
df.shape

(7043, 21)

Check and Handle Missing Values/Duplicated Data

In [16]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [9]:
df.describe

<bound method NDFrame.describe of       customerID  gender  SeniorCitizen Partner Dependents  tenure  \
0     7590-VHVEG  Female              0     Yes         No       1
1     5575-GNVDE    Male              0      No         No      34
2     3668-QPYBK    Male              0      No         No       2
3     7795-CFOCW    Male              0      No         No      45
4     9237-HQITU  Female              0      No         No       2
...          ...     ...            ...     ...        ...     ...
7038  6840-RESVB    Male              0     Yes        Yes      24
7039  2234-XADUH  Female              0     Yes        Yes      72
7040  4801-JZAZL  Female              0     Yes        Yes      11
7041  8361-LTMKD    Male              1     Yes         No       4
7042  3186-AJIEK    Male              0      No         No      66

     PhoneService     MultipleLines InternetService OnlineSecurity  ...  \
0              No  No phone service             DSL             No  ...
1             Yes                No             DSL            Yes  ...
2             Yes                No             DSL            Yes  ...
3              No  No phone service             DSL            Yes  ...
4             Yes                No     Fiber optic             No  ...
...           ...               ...             ...            ...  ...
7038          Yes               Yes             DSL            Yes  ...
7039          Yes               Yes     Fiber optic             No  ...
7040           No  No phone service             DSL            Yes  ...
7041          Yes               Yes     Fiber optic             No  ...
7042          Yes                No     Fiber optic            Yes  ...

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0                  No          No          No              No  Month-to-month
1                 Yes          No          No              No        One year
2                  No          No          No              No  Month-to-month
3                 Yes         Yes          No              No        One year
4                  No          No          No              No  Month-to-month
...               ...         ...         ...             ...             ...
7038              Yes         Yes         Yes             Yes        One year
7039              Yes          No         Yes             Yes        One year
7040               No          No          No              No  Month-to-month
7041               No          No          No              No  Month-to-month
7042              Yes         Yes         Yes             Yes        Two year

     PaperlessBilling              PaymentMethod MonthlyCharges  TotalCharges  \
0                 Yes           Electronic check          29.85         29.85
1                  No               Mailed check          56.95        1889.5
2                 Yes               Mailed check          53.85        108.15
3                  No  Bank transfer (automatic)          42.30       1840.75
4                 Yes           Electronic check          70.70        151.65
...               ...                        ...            ...           ...
7038              Yes               Mailed check          84.80        1990.5
7039              Yes    Credit card (automatic)         103.20        7362.9
7040              Yes           Electronic check          29.60        346.45
7041              Yes               Mailed check          74.40         306.6
7042              Yes  Bank transfer (automatic)         105.65        6844.5

     Churn
0       No
1       No
2      Yes
3       No
4      Yes
...    ...
7038    No
7039    No
7040    No
7041   Yes
7042    No

[7043 rows x 21 columns]>

In [10]:
column_names = df.columns.tolist()

# Print the column names
print(column_names)

['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn']

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [12]:
missing_values = df.isnull().sum()

# Print the count of missing values for each column
print(missing_values)

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [25]:
df[df["TotalCharges"].str.contains(" ")]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,4472-LVYGI,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,,No
753,3115-CZMZD,Male,0,No,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,,No
936,5709-LVOEQ,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,...,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,,No
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,,No
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,,No
3331,7644-OMVMY,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,,No
3826,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,,No
4380,2520-SGTTA,Female,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,,No
5218,2923-ARZLG,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,,No
6670,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,...,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,,No
6754,2775-SEFEE,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,...,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,,No

There are 11 datas from the 'TotalCharges columns that contain white spaces

In [28]:
# exclude rows with TotalCharges culomns contains white space
df = df.loc[~df['TotalCharges'].str.contains(' ')]

# transform TotalCharge col to float
df['TotalCharges'] = df['TotalCharges'].astype(float)

AttributeError: Can only use .str accessor with string values!

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7032 non-null   object
 1   gender            7032 non-null   object
 2   SeniorCitizen     7032 non-null   int64
 3   Partner           7032 non-null   object
 4   Dependents        7032 non-null   object
 5   tenure            7032 non-null   int64
 6   PhoneService      7032 non-null   object
 7   MultipleLines     7032 non-null   object
 8   InternetService   7032 non-null   object
 9   OnlineSecurity    7032 non-null   object
 10  OnlineBackup      7032 non-null   object
 11  DeviceProtection  7032 non-null   object
 12  TechSupport       7032 non-null   object
 13  StreamingTV       7032 non-null   object
 14  StreamingMovies   7032 non-null   object
 15  Contract          7032 non-null   object
 16  PaperlessBilling  7032 non-null   object
 17  PaymentMethod     7032 non-null   object
 18  MonthlyCharges    7032 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7032 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.2+ MB

In [30]:
df.isna().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [31]:
df.duplicated().sum()

0

Normalization of Numerical Features:

We'll use the Min-Max Scaler to normalize the numerical features (tenure, MonthlyCharges, TotalCharges) to a common scale between 0 and 1.

In [33]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df[['tenure', 'MonthlyCharges', 'TotalCharges']] = scaler.fit_transform(df[['tenure', 'MonthlyCharges', 'TotalCharges']])

C:\Users\SHANNON\AppData\Local\Temp\ipykernel_11428\2078885912.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['tenure', 'MonthlyCharges', 'TotalCharges']] = scaler.fit_transform(df[['tenure', 'MonthlyCharges', 'TotalCharges']])

In [40]:
from sklearn.preprocessing import LabelEncoder, StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

# Assuming you have a DataFrame called 'df' with categorical columns
# Select categorical columns for one-hot encoding
categorical_columns = df.select_dtypes(include=['object']).columns

# Perform one-hot encoding on the selected categorical columns
df_encoded = pd.get_dummies(df, columns=categorical_columns, drop_first=True)

# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(df_encoded.drop('Churn_Yes', axis=1), df_encoded['Churn_Yes'], test_size=0.2, random_state=42)

# Create an XGBoost classifier
xgb = XGBClassifier(random_state=42)

# Train the model
xgb.fit(X_train, y_train)

# Make predictions
y_pred = xgb.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)
report = classification_report(y_test, y_pred)

print(f'Accuracy: {accuracy}')
print(f'Confusion Matrix:\n{confusion}')
print(f'Classification Report:\n{report}')

Accuracy: 0.7633262260127932
Confusion Matrix:
[[898 135]
 [198 176]]
Classification Report:
              precision    recall  f1-score   support

       False       0.82      0.87      0.84      1033
        True       0.57      0.47      0.51       374

    accuracy                           0.76      1407
   macro avg       0.69      0.67      0.68      1407
weighted avg       0.75      0.76      0.76      1407

In [41]:
from sklearn.preprocessing import LabelEncoder, StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

# Assuming you have a DataFrame called 'df' with categorical columns
# Select categorical columns for one-hot encoding
categorical_columns = df.select_dtypes(include=['object']).columns

# Perform one-hot encoding on the selected categorical columns
df_encoded = pd.get_dummies(df, columns=categorical_columns, drop_first=True)

# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(df_encoded.drop('Churn_Yes', axis=1), df_encoded['Churn_Yes'], test_size=0.3, random_state=42)


# Create an XGBoost classifier
xgb = XGBClassifier(random_state=42)

# Train the model
xgb.fit(X_train, y_train)

# Make predictions
y_pred = xgb.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)
report = classification_report(y_test, y_pred)

print(f'Accuracy: {accuracy}')
print(f'Confusion Matrix:\n{confusion}')
print(f'Classification Report:\n{report}')

      SeniorCitizen    tenure  MonthlyCharges  TotalCharges  \
3946              0  0.112676        0.400498      0.060126
3394              0  0.352113        0.430846      0.180377
1635              0  0.028169        0.514428      0.023269
4088              0  0.084507        0.550746      0.057835
1886              0  0.929577        0.419403      0.454062
...             ...       ...             ...           ...
3778              0  0.028169        0.319900      0.013668
5199              0  0.704225        0.927861      0.655949
5235              0  0.112676        0.625871      0.088351
5399              0  0.690141        0.014925      0.111961
862               1  0.267606        0.551244      0.166709

      customerID_0003-MKNFE  customerID_0004-TLHLJ  customerID_0011-IGKFF  \
3946                  False                  False                  False
3394                  False                  False                  False
1635                  False                  False                  False
4088                  False                  False                  False
1886                  False                  False                  False
...                     ...                    ...                    ...
3778                  False                  False                  False
5199                  False                  False                  False
5235                  False                  False                  False
5399                  False                  False                  False
862                   False                  False                  False

      customerID_0013-EXCHZ  customerID_0013-MHZWF  customerID_0013-SMEOE  \
3946                  False                  False                  False
3394                  False                  False                  False
1635                  False                  False                  False
4088                  False                  False                  False
1886                  False                  False                  False
...                     ...                    ...                    ...
3778                  False                  False                  False
5199                  False                  False                  False
5235                  False                  False                  False
5399                  False                  False                  False
862                   False                  False                  False

      ...  StreamingTV_No internet service  StreamingTV_Yes  \
3946  ...                            False             True
3394  ...                            False            False
1635  ...                            False             True
4088  ...                            False            False
1886  ...                            False            False
...   ...                              ...              ...
3778  ...                            False            False
5199  ...                            False             True
5235  ...                            False            False
5399  ...                             True            False
862   ...                            False            False

      StreamingMovies_No internet service  StreamingMovies_Yes  \
3946                                False                 True
3394                                False                False
1635                                False                 True
4088                                False                False
1886                                False                False
...                                   ...                  ...
3778                                False                False
5199                                False                 True
5235                                False                False
5399                                 True                False
862                                 False                False

      Contract_One year  Contract_Two year  PaperlessBilling_Yes  \
3946              False              False                 False
3394               True              False                 False
1635               True              False                  True
4088              False              False                 False
1886              False               True                  True
...                 ...                ...                   ...
3778              False              False                 False
5199               True              False                  True
5235              False              False                  True
5399               True              False                 False
862               False              False                  True

      PaymentMethod_Credit card (automatic)  PaymentMethod_Electronic check  \
3946                                  False                           False
3394                                  False                            True
1635                                  False                            True
4088                                  False                            True
1886                                  False                           False
...                                     ...                             ...
3778                                  False                           False
5199                                  False                            True
5235                                  False                            True
5399                                  False                           False
862                                   False                            True

      PaymentMethod_Mailed check
3946                        True
3394                       False
1635                       False
4088                       False
1886                       False
...                          ...
3778                       False
5199                       False
5235                       False
5399                       False
862                        False

[4922 rows x 7061 columns]       SeniorCitizen    tenure  MonthlyCharges  TotalCharges  \
2481              1  0.845070        0.067164      0.171123
6784              0  0.253521        0.064179      0.051587
6125              0  0.169014        0.835821      0.154650
3052              0  0.507042        0.366169      0.232166
4099              0  0.070423        0.111443      0.016461
...             ...       ...             ...           ...
2763              0  0.887324        0.624876      0.590417
6747              0  0.718310        0.171144      0.223881
1700              0  0.647887        0.021891      0.106647
1099              0  0.056338        0.372637      0.027764
4720              1  0.887324        0.834328      0.769594

      customerID_0003-MKNFE  customerID_0004-TLHLJ  customerID_0011-IGKFF  \
2481                  False                  False                  False
6784                  False                  False                  False
6125                  False                  False                  False
3052                  False                  False                  False
4099                  False                  False                  False
...                     ...                    ...                    ...
2763                  False                  False                  False
6747                  False                  False                  False
1700                  False                  False                  False
1099                  False                  False                  False
4720                  False                  False                  False

      customerID_0013-EXCHZ  customerID_0013-MHZWF  customerID_0013-SMEOE  \
2481                  False                  False                  False
6784                  False                  False                  False
6125                  False                  False                  False
3052                  False                  False                  False
4099                  False                  False                  False
...                     ...                    ...                    ...
2763                  False                  False                  False
6747                  False                  False                  False
1700                  False                  False                  False
1099                  False                  False                  False
4720                  False                  False                  False

      ...  StreamingTV_No internet service  StreamingTV_Yes  \
2481  ...                             True            False
6784  ...                             True            False
6125  ...                            False             True
3052  ...                            False            False
4099  ...                            False            False
...   ...                              ...              ...
2763  ...                            False            False
6747  ...                            False            False
1700  ...                             True            False
1099  ...                            False            False
4720  ...                            False             True

      StreamingMovies_No internet service  StreamingMovies_Yes  \
2481                                 True                False
6784                                 True                False
6125                                False                 True
3052                                False                False
4099                                False                False
...                                   ...                  ...
2763                                False                False
6747                                False                False
1700                                 True                False
1099                                False                False
4720                                False                 True

      Contract_One year  Contract_Two year  PaperlessBilling_Yes  \
2481              False               True                 False
6784              False              False                 False
6125              False              False                  True
3052              False              False                  True
4099              False              False                 False
...                 ...                ...                   ...
2763              False              False                 False
6747               True              False                 False
1700              False               True                 False
1099              False              False                  True
4720               True              False                 False

      PaymentMethod_Credit card (automatic)  PaymentMethod_Electronic check  \
2481                                  False                           False
6784                                  False                           False
6125                                   True                           False
3052                                  False                           False
4099                                  False                           False
...                                     ...                             ...
2763                                  False                            True
6747                                  False                           False
1700                                  False                           False
1099                                  False                           False
4720                                  False                            True

      PaymentMethod_Mailed check
2481                       False
6784                       False
6125                       False
3052                        True
4099                       False
...                          ...
2763                       False
6747                        True
1700                       False
1099                        True
4720                       False

[2110 rows x 7061 columns] 3946     True
3394    False
1635    False
4088     True
1886    False
        ...
3778    False
5199    False
5235    False
5399    False
862      True
Name: Churn_Yes, Length: 4922, dtype: bool 2481    False
6784    False
6125     True
3052    False
4099    False
        ...
2763    False
6747    False
1700    False
1099    False
4720    False
Name: Churn_Yes, Length: 2110, dtype: bool

Accuracy: 0.7691943127962085
Confusion Matrix:
[[1334  215]
 [ 272  289]]
Classification Report:
              precision    recall  f1-score   support

       False       0.83      0.86      0.85      1549
        True       0.57      0.52      0.54       561

    accuracy                           0.77      2110
   macro avg       0.70      0.69      0.69      2110
weighted avg       0.76      0.77      0.77      2110